name: custom_components
description: All my flutter custom components that I build.
version: 0.0.2
author: LyhourChhen
homepage: https://github.com/LyhourChhen/custom_components

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
