name: custom_components
description: All my flutter custom components that I build.
version: 0.0.2
author: LyhourChhen
homepage: https://github.com/LyhourChhen/custom_components

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_i18n: ^0.19.1
  cached_network_image: ^2.2.0+1
  like_button: ^1.0.3
  flutter_hooks: ^0.13.2
  infinite_scroll_pagination: ^2.0.1
flutter:
