name: Dart CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: "Trying to publish without confirmation"
      run: pub publish --force
#     - name: Install dependencies
#       run: pub get
#     - name: Run tests
#       run: pub run test
