name: Test widgets | components.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter ${{ matrix.flutter-version }}
      id: flutter
      if: "!startsWith(matrix.bot, 'dart')"
      uses: DanTup/gh-actions/setup-flutter@master
      with:
        channel: stable
        
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
